version: "3"
services:
  adapter_webui:
    build: .
    image: adapter_webui
    volumes:
      - ./adapter.conf:/etc/nginx/conf.d/adapter.conf
    ports:
      - "8200:80"
    container_name: adapter_webui
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/adapter.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
